using System;
using System.Collections.Generic;
using System.Text;

namespace ClothingStoreFranchise.NetCore.Common.Types
{
    /// <summary>
    /// This interface must be implemented by those entities
    /// which don't have a unique, immutable field capable of being its AppId
    /// </summary>
    public interface IAutoGeneratedAppId
    {
        string AutoGeneratedAppId { get; set; }
    }
}
